#! /bin/bash

APP="ucsm_state_manager"
FLASHLOCATION="/opt/flash/cisco/bin/${APP}"
INITRAMFSLOCATION="/opt/cisco/bin/${APP}"

if [ -e ${INITRAMFSLOCATION} ]; then
	exec ${INITRAMFSLOCATION};
elif [ -e ${FLASHLOCATION} ]; then
	exec ${FLASHLOCATION};
fi

